### ISSUE TITLE
ProfileSelectorSupplier for org.apache.maven.settings.Profile

### ISSUE THREAD

**Issue by grgrzybek** [maveniverse/mima#58]
Currently `eu.maveniverse.maven.mima.runtime.standalonestatic.ProfileSelectorSupplier` gives `org.apache.maven.model.profile.ProfileSelector` which may select active profiles from a collection of model profiles.

When working with `org.apache.maven.settings.Profile` instances (from Settings) I have to translate settings to model profiles.

I see no `ProfileSelector` interface for settings profiles, so it may not be possible, but if there's an easy way to get a ProfileSelector for settings profiles, it'd be great. Please reject otherwise.

**Comment by cstamas** [comment]
See here, https://github.com/maveniverse/mima/blob/main/context/src/main/java/eu/maveniverse/maven/mima/context/ContextOverrides.java#L626-L652

And those are fed into profile activation context:
https://github.com/maveniverse/mima/blob/main/runtime/standalone-shared/src/main/java/eu/maveniverse/maven/mima/runtime/shared/StandaloneRuntimeSupport.java#L302

**Comment by grgrzybek** [comment]
But ContextOverrides gives you active profile IDs.
When I load settings, I get (`org.apache.maven.settings.Settings#getProfiles()`) a list of `org.apache.maven.settings.Profile` instances. To make activation work, I have to deep-copy between these two:
* org.apache.maven.settings.Profile
* org.apache.maven.model.Profile

at least all the activation pojos:
* org.apache.maven.settings.Activation → org.apache.maven.model.Activation
* org.apache.maven.settings.ActivationFile → org.apache.maven.model.ActivationFile
* org.apache.maven.settings.ActivationProperty → org.apache.maven.model.ActivationProperty
* org.apache.maven.settings.ActivationOS → org.apache.maven.model.ActivationOS

here's what I did in Pax UR:
```java
ProfileSelector selector = new ProfileSelectorSupplier().get();

List<Profile> settingsProfiles = settings.getProfiles();
List<org.apache.maven.model.Profile> profiles = new ArrayList<>(settingsProfiles.size());
settingsProfiles.forEach(p -> {
    org.apache.maven.model.Profile mp = new org.apache.maven.model.Profile();
    mp.setSource(org.apache.maven.model.Profile.SOURCE_SETTINGS);
    mp.setId(p.getId());

    Activation a = p.getActivation();
    if (a != null) {
        org.apache.maven.model.Activation ma = new org.apache.maven.model.Activation();
        mp.setActivation(ma);
        ma.setActiveByDefault(a.isActiveByDefault());

        ActivationFile af = a.getFile();
        if (af != null) {
            org.apache.maven.model.ActivationFile maf = new org.apache.maven.model.ActivationFile();
            maf.setExists(af.getExists());
            maf.setMissing(af.getMissing());
            ma.setFile(maf);
        }
        String aj = a.getJdk();
        if (aj != null) {
            ma.setJdk(aj);
        }
        ActivationProperty ap = a.getProperty();
        if (ap != null) {
            org.apache.maven.model.ActivationProperty map = new org.apache.maven.model.ActivationProperty();
            map.setName(ap.getName());
            map.setValue(ap.getValue());
            ma.setProperty(map);
        }
        ActivationOS ao = a.getOs();
        if (ao != null) {
            org.apache.maven.model.ActivationOS mao = new org.apache.maven.model.ActivationOS();
            mao.setName(ao.getName());
            mao.setVersion(ao.getVersion());
            mao.setArch(ao.getArch());
            mao.setFamily(ao.getFamily());
            ma.setOs(mao);
        }
    }
    // skip other profile data, because we care only about activation here

    profiles.add(mp);
});

DefaultProfileActivationContext context = new DefaultProfileActivationContext();
context.setActiveProfileIds(settings.getActiveProfiles());
// we can't specify it via settings.xml - it's for `-P-xxx` mvn invocation
context.setInactiveProfileIds(Collections.emptyList());

// we need properties, but we have only PropertyResolver. It delegates to PID and BundleContext
// properties, but let's stick to system properties only
context.setSystemProperties(new Properties(System.getProperties()));

ModelProblemCollector problemCollector = new ModelProblemCollector() {
    @Override
    public void add(ModelProblemCollectorRequest req) {
        LOGGER.warn(req.getMessage() + " " + req.getLocation());
    }
};
List<org.apache.maven.model.Profile> activeProfiles = selector.getActiveProfiles(profiles, context, problemCollector);
Set<String> profileNames = new LinkedHashSet<>();
activeProfiles.forEach(ap -> profileNames.add(ap.getId()));

return profileNames;
```

**Comment by cstamas** [comment]
But MIMA will _process_ those profiles for you (lift remote repositories, lift properties, etc). Why do you want to go so "deep"? Is there something missing that MIMA does not process for you?

**Comment by cstamas** [comment]
In other words, what you want to achieve?

**Comment by grgrzybek** [comment]
> In other words, what you want to achieve?

I want to read profiles from settings.xml (not from pom.xml) and use some "selector" to choose the active ones (by property/os/file/jdk or byDefault).

In Pax URL 2.6.14 I had this: https://github.com/ops4j/org.ops4j.pax.url/blob/url-2.6.14/pax-url-aether/src/main/java/org/ops4j/pax/url/mvn/internal/config/MavenConfigurationImpl.java#L338-L349

```java
    private Collection<String> getActiveProfiles(boolean alsoActiveByDefault) {
        Set<String> profileNames = new LinkedHashSet<String>(settings.getActiveProfiles());
        if (alsoActiveByDefault) {
            for (Profile profile : settings.getProfiles()) {
                if (profile.getActivation() != null && profile.getActivation().isActiveByDefault()) {
                    // TODO: check other activations - file/jdk/os/property?
                    profileNames.add(profile.getId());
                }
            }
        }
        return profileNames;
    }
```

now I wanted to use `eu.maveniverse.maven.mima.runtime.standalonestatic.ProfileSelectorSupplier` → `org.apache.maven.model.profile.DefaultProfileSelector`, but it works on different profiles (from pom/model, not from settings).

**Comment by cstamas** [comment]
But why do you want to do things that MIMA already does for you? As I said above, the "effective settings" you end up with being in use do have all the proper profiles activated, processed and applied...

Am trying to get "higher level" picture why you want to "fiddle" with profile activation at all, when it already happens... or you have some extra logic? Maybe MIMA does "too much" for your use case?

**Comment by grgrzybek** [comment]
Ha - now I've found `eu.maveniverse.maven.mima.runtime.shared.StandaloneRuntimeSupport#convertFromSettingsProfile()` :) And I'm looking at `eu.maveniverse.maven.mima.runtime.shared.StandaloneRuntimeSupport#buildContext()`.
This is exactly what I needed. Thanks!
