### ISSUE TITLE
Make MIMA Java module friendly

### ISSUE THREAD

**Issue by cstamas** [maveniverse/mima#71]

**Comment by neilcsmith-net** [comment]
:+1: MIMA looks like it might be a good fit for something I'm working on, but working on module path is a requirement (ideally in an upstream supported way).

**Comment by cstamas** [comment]
I have to admit, I don't have quite much knowledge in JPMS/jigsaw area, so originally I envisioned this as an "exercise to learn it" :smile: but simply cannot get to it. 

Moreover, as I was looking, the Eclipse SISU (JSR DI Maven uses natively) may be somewhat in contradiction to JPMS requirements, but I'd be fine if we could modularize the "static" runtime only...
