### ISSUE TITLE
BOM use-case for classpath and resolve commands

### ISSUE THREAD

**Issue by rsvoboda** [maveniverse/mima#91]
`classpath` and `resolve` commands could be extended to cover use-case with BOM.

Instead of GAV users would specify `artifact_GA` and `--bom=bom_GAV`

The downside is that the command description would become a bit more complicated

**Comment by cstamas** [comment]
Howdy, thanks for the issue.

What do you mean specifically by "use-case with BOM"? It is a bit unclear to me what you'd expect as input (params) and what would be the output?

**Comment by rsvoboda** [comment]
Here is an example:
```
mima classpath org.hibernate.orm:hibernate-core --bom io.quarkus.platform:quarkus-bom:3.7.1
mima resolve org.hibernate.orm:hibernate-core --bom io.quarkus.platform:quarkus-bom:3.7.1
```

The idea would be to resolve dependencies and their versions based on the definitions in BOM and not necessarily the versions defined in pom file of the artifact.

`mima resolve` would also print the version of the defined GA - `Resolving org.hibernate.orm:hibernate-core:VERSION` for the example above.
